### ISSUE TITLE
Build Failed: libman restore failed

### ISSUE THREAD

**Issue by FeynmanLoo** [EdiWang/LinkForwarder#33]
[LIB002]: "jquery@3.4.1" 库无法由 "cdnjs" 提供程序解析
[LIB002]: "twitter-bootstrap@4.3.1" 库无法由 "cdnjs" 提供程序解析
[LIB002]: "jquery.qrcode@1.0" 库无法由 "cdnjs" 提供程序解析
[LIB002]: "jquery-validate@1.19.0" 库无法由 "cdnjs" 提供程序解析
[LIB002]: "jquery-validation-unobtrusive@3.2.11" 库无法由 "cdnjs" 提供程序解析
[LIB002]: "popper.js@1.15.0" 库无法由 "cdnjs" 提供程序解析
[LIB002]: "datatables@1.10.19" 库无法由 "cdnjs" 提供程序解析
[LIB002]: "toastr.js@2.1.4" 库无法由 "cdnjs" 提供程序解析
[LIB002]: "Chart.js@2.8.0" 库无法由 "cdnjs" 提供程序解析
[LIB002]: "jquery-dateFormat@1.0" 库无法由 "cdnjs" 提供程序解析

**Comment by EdiWang** [comment]
@FeynmanLoo If you are in China, please 科学上网.
