### ISSUE TITLE
Where is the Response type coming from?

### ISSUE THREAD

**Issue by os1r1s110** [EdiWang/LinkForwarder#50]
Hey there, nice project. I'm trying to implement something similar in my app, and was wondering where the `Response<T>` was coming from?

I think I figured out it was coming from `Edi.Practice.RequestResponse`, but this is not listed in the .sln file as a dependency of any kind...

**Comment by EdiWang** [comment]
@os1r1s110 it is included in the project dependency: 

https://github.com/EdiWang/LinkForwarder/blob/master/src/LinkForwarder.Web/LinkForwarder.Web.csproj#L22
